version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 3000:80

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3001:80
    depends_on:
      - backend
