version: '3'

services:
  backend:
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 3000:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 4200:4200
      - 49153:49153
    depends_on:
      - backend
